version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

# Options for custom base configuration file
#clash_rule_base = "base/forcerule.yml"
#surge_rule_base = "base/surge.conf"
#surfboard_rule_base = "base/surfboard.conf"
#mellow_rule_base = "base/mellow.conf"
#quan_rule_base = "base/quan.conf"
#quanx_rule_base = "base/quanx.conf"

# Options for adding emojis
add_emoji = true
remove_old_emoji = true

# Options for filtering nodes
#include_remarks = ["广港IEPL|沪日|沪韩|jx2azhk|SS|懒人|新加坡 0[12]|台湾.*\^"]
#exclude_remarks = []

[[rulesets]]
import = "https://raw.githubusercontent.com/xiaochong113/bypass/master/file/rulesets.toml"

[[custom_groups]]
import = "https://raw.githubusercontent.com/xiaochong113/bypass/master/file/groups.toml"

[[node_pref.rename_node]]
import = "https://raw.githubusercontent.com/xiaochong113/bypass/master/file/rename_node.toml"

[[emojis.emoji]]
match = '(懒人)'
emoji = '🦥'


[[template_args]]
#key = "clash.dns.port"
#value = "5353"
