[[emoji]]
match = "(懒人)"
emoji = "🦥"

[[emoji]]
match = "(香港|HK|沪港|广港|HGC|azhk)"
emoji = "🇭🇰"

[[emoji]]
match = "(台湾|TPE|HiNet|TW)"
emoji = "🇹🇼"

[[emoji]]
match = "(日本|JP|沪日|湘日)"
emoji = "🇯🇵"

[[emoji]]
match = "(韩国|沪韩)"
emoji = "🇰🇷"

[[emoji]]
match = "(新加坡|狮城|SG|OCI3)"
emoji = "🇸🇬"

[[emoji]]
match = "(美国|US|沪美)"
emoji = "🇺🇸"

[[emoji]]
match = "(Ascension|阿森松)"
emoji = "🇦🇨"

[[emoji]]
match = "(?i:\\bUAE\\b|Dubai|阿联酋|迪拜)"
emoji = "🇦🇪"

[[emoji]]
match = "(阿尔巴尼亚|Albania)"
emoji = "🇦🇱"

[[emoji]]
match = "(Argentina|阿根廷)"
emoji = "🇦🇷"

[[emoji]]
match = "(Austria|Vienna|奥地利|维也纳)"
emoji = "🇦🇹"

[[emoji]]
match = "(?i:\\bAU[S]?\\b|Australia|Sydney|澳大利亚|澳洲|悉尼)"
emoji = "🇦🇺"

[[emoji]]
match = "(阿塞拜疆|Azerbaijan)"
emoji = "🇦🇿"

[[emoji]]
match = "(波黑共和国|波士尼亚与赫塞哥维纳|Bosnia|Herzegovina)"
emoji = "🇧🇦"

[[emoji]]
match = "(Belgium|比利时)"
emoji = "🇧🇪"

[[emoji]]
match = "(保加利亚|Bulgaria)"
emoji = "🇧🇬"

[[emoji]]
match = "(Brazil|Paulo|巴西|圣保罗)"
emoji = "🇧🇷"

[[emoji]]
match = "(?i:\\bCA[N]?\\b|Canada|Toronto|Montreal|Vancouver|加拿大|蒙特利尔|温哥华|楓葉|枫叶)"
emoji = "🇨🇦"

[[emoji]]
match = "(Switzerland|Zurich|瑞士|苏黎世)"
emoji = "🇨🇭"

[[emoji]]
match = "(智利|Chile)"
emoji = "🇨🇱"

[[emoji]]
match = "(Colombia|哥伦比亚)"
emoji = "🇨🇴"

