[[custom_groups]]
name = "🌏 Proxynd"
type = "select"
rule = ["!!GROUPID=0!!(广港IEPLS)", "!!GROUPID=1!!(香港ISL$|台湾|新加坡)"]

[[custom_groups]]
name = "💞 SocialM"
type = "select"
rule = ["!!GROUPID=0!!(沪日IPLC)", "!!GROUPID=1!!(日本)"]

[[custom_groups]]
name = "🔮 Google®"
type = "select"
rule = ["!!GROUPID=0!!(广港IEPLS)", "!!GROUPID=1!!(香港ISLN)"]

[[custom_groups]]
name = "📺 EmbyVip"
type = "select"
rule = ["!!GROUPID=0!!(广港IEPL$|azhk)", "[]DIRECT"]

[[custom_groups]]
name = "🎥 EmbyDmm"
type = "select"
rule = ["!!GROUPID=0!!(沪韩|沪日IEPL)"]

[[custom_groups]]
name = "📽️ NetFlix"
type = "select"
rule = ["!!GROUPID=2!!(懒人|新加坡|台湾)"]
