# [[rulesets]]
# group = ""
# ruleset = ""
# type = "surge-ruleset"
# interval = 86400

# [[rulesets]]
# group = ""
# ruleset = ""
# type = "surge-ruleset"
# interval = 86400

# [[rulesets]]
# group = ""
# ruleset = ""
# type = "surge-ruleset"
# interval = 86400
